;设置规则标志位
surge_ruleset=DIRECT,rules/ACL4SSR/Clash/LocalAreaNetwork.list
surge_ruleset=DIRECT,rules/ACL4SSR/Clash/UnBan.list
surge_ruleset=🛑 拦截连接,https://zhyu-gao.github.io/config/myreject.list
surge_ruleset=🛑 拦截连接,rules/ACL4SSR/Clash/BanAD.list
surge_ruleset=🛑 拦截连接,rules/ACL4SSR/Clash/BanProgramAD.list
surge_ruleset=🎥 NETFLIX,rules/ACL4SSR/Clash/Netflix.list
surge_ruleset=📲 电报吹水,rules/ACL4SSR/Clash/Telegram.list
surge_ruleset=🌍 国际媒体,rules/ACL4SSR/Clash/ProxyMedia.list
surge_ruleset=🍎 苹果服务,rules/ACL4SSR/Clash/Apple.list
surge_ruleset=🔰 国外网站,https://zhyu-gao.github.io/config/myproxy.list
surge_ruleset=🔰 国外网站,rules/ACL4SSR/Clash/ProxyLite.list
surge_ruleset=DIRECT,rules/ACL4SSR/Clash/ChinaDomain.list
surge_ruleset=DIRECT,rules/ACL4SSR/Clash/ChinaCompanyIp.list
surge_ruleset=DIRECT,[]GEOIP,CN
surge_ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🔰 国外网站`select`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇺🇲 美国节点0.1`[]🇯🇵 日本节点1`[]🇯🇵 日本节点2`[]🇺🇲 美国节点`[]🇳🇱 荷兰节点`[]🇩🇪 德国节点`[]📌 手动切换`[]DIRECT
custom_proxy_group=📲 电报吹水`select`[]🔰 国外网站`[]🇺🇲 美国节点0.1`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点1`[]🇯🇵 日本节点2`[]🇺🇲 美国节点`[]🇳🇱 荷兰节点`[]🇩🇪 德国节点`[]📌 手动切换`[]DIRECT
custom_proxy_group=🎥 NETFLIX`select`[]🔰 国外网站`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇺🇲 美国节点0.1`[]🇯🇵 日本节点1`[]🇯🇵 日本节点2`[]🇺🇲 美国节点`[]🇳🇱 荷兰节点`[]🇩🇪 德国节点`[]🎥 奈非节点`[]DIRECT
custom_proxy_group=🌍 国际媒体`select`[]🔰 国外网站`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇺🇲 美国节点0.1`[]🇯🇵 日本节点1`[]🇯🇵 日本节点2`[]🇺🇲 美国节点`[]🇳🇱 荷兰节点`[]🇩🇪 德国节点`[]📌 手动切换`[]DIRECT
custom_proxy_group=🌏 港台媒体`select`[]DIRECT`[]🔰 国外网站`[]📌 手动切换`[]🇭🇰 香港节点`[]🇨🇳 台湾节点
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🔰 国外网站`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇺🇲 美国节点0.1`[]🇯🇵 日本节点1`[]🇯🇵 日本节点2`[]🇺🇲 美国节点`[]🇳🇱 荷兰节点`[]🇩🇪 德国节点`[]📌 手动切换
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🔰 国外网站`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇺🇲 美国节点0.1`[]🇯🇵 日本节点1`[]🇯🇵 日本节点2`[]🇺🇲 美国节点`[]🇳🇱 荷兰节点`[]🇩🇪 德国节点`[]📌 手动切换
custom_proxy_group=🇭🇰 香港节点`url-test`(HongKong-HK1)`http://www.gstatic.com/generate_204`500
custom_proxy_group=🇨🇳 台湾节点`url-test`(Taiwan-TW1)`http://www.gstatic.com/generate_204`500
custom_proxy_group=🇺🇲 美国节点0.1`url-test`(UnitedStates-FM2)`http://www.gstatic.com/generate_204`500
custom_proxy_group=🇯🇵 日本节点1`url-test`(Japan-TY)`http://www.gstatic.com/generate_204`500
custom_proxy_group=🇯🇵 日本节点2`url-test`(Japan-OS)`http://www.gstatic.com/generate_204`500
custom_proxy_group=🇺🇲 美国节点`url-test`(UnitedStates-FM1)`http://www.gstatic.com/generate_204`500
custom_proxy_group=🇳🇱 荷兰节点`url-test`(Netherlands-NL1)`http://www.gstatic.com/generate_204`500
custom_proxy_group=🇩🇪 德国节点`url-test`(Germany-DE)`http://www.gstatic.com/generate_204`500
custom_proxy_group=📌 手动切换`select`.*
custom_proxy_group=🎥 奈非节点`select`(NF|解锁|Netflix|NETFLIX)
custom_proxy_group=🛑 拦截连接`select`[]REJECT`[]DIRECT
;设置分组标志位